# Generated by Django 5.2.8 on 2025-11-24 02:12

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_number', models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('case_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('suspended', 'Suspended'), ('archived', 'Archived')], default='active', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('case_type', models.CharField(choices=[('fraud', 'Fraud'), ('cybercrime', 'Cybercrime'), ('data_breach', 'Data Breach'), ('intellectual_property', 'Intellectual Property'), ('general', 'General')], default='general', max_length=30)),
                ('date_opened', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_closed', models.DateTimeField(blank=True, null=True)),
                ('lead_investigator', models.CharField(blank=True, max_length=200)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('jurisdiction', models.CharField(blank=True, max_length=200)),
                ('incident_date', models.DateTimeField(blank=True, null=True)),
                ('incident_location', models.CharField(blank=True, max_length=500)),
                ('evidence_location', models.CharField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cases',
                'ordering': ['-date_opened'],
            },
        ),
        migrations.CreateModel(
            name='CasePerson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('suspect', 'Suspect'), ('victim', 'Victim'), ('witness', 'Witness'), ('investigator', 'Investigator'), ('expert', 'Expert'), ('other', 'Other')], max_length=20)),
                ('involvement_description', models.TextField(blank=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_primary', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'case_persons',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('report', 'Report'), ('warrant', 'Warrant'), ('subpoena', 'Subpoena'), ('affidavit', 'Affidavit'), ('memo', 'Memo'), ('photo', 'Photo'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/')),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('file_type', models.CharField(blank=True, max_length=100)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('is_confidential', models.BooleanField(default=False)),
                ('access_level', models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('restricted', 'Restricted'), ('classified', 'Classified')], default='internal', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'documents',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evidence_number', models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('evidence_type', models.CharField(choices=[('digital', 'Digital'), ('physical', 'Physical'), ('document', 'Document'), ('media', 'Media'), ('other', 'Other')], max_length=20)),
                ('item_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('collected_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('collected_by', models.CharField(blank=True, max_length=200)),
                ('location_found', models.CharField(blank=True, max_length=500)),
                ('chain_of_custody', models.JSONField(blank=True, default=list)),
                ('storage_location', models.CharField(blank=True, max_length=500)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='evidence/%Y/%m/%d/')),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('file_type', models.CharField(blank=True, max_length=100)),
                ('hash_md5', models.CharField(blank=True, max_length=32)),
                ('hash_sha1', models.CharField(blank=True, max_length=40)),
                ('hash_sha256', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('collected', 'Collected'), ('analyzed', 'Analyzed'), ('returned', 'Returned'), ('destroyed', 'Destroyed'), ('archived', 'Archived')], default='collected', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'evidence',
                'ordering': ['-collected_date'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('deadline_reminder', 'Deadline Reminder'), ('status_change', 'Status Change'), ('new_evidence', 'New Evidence'), ('task_assigned', 'Task Assigned'), ('system_alert', 'System Alert'), ('other', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('recipient', models.CharField(blank=True, max_length=200)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('ssn', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(default='USA', max_length=100)),
                ('person_type', models.CharField(choices=[('suspect', 'Suspect'), ('victim', 'Victim'), ('witness', 'Witness'), ('investigator', 'Investigator'), ('expert', 'Expert'), ('other', 'Other')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'persons',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('task_type', models.CharField(choices=[('investigation', 'Investigation'), ('analysis', 'Analysis'), ('documentation', 'Documentation'), ('evidence', 'Evidence'), ('legal', 'Legal'), ('meeting', 'Meeting'), ('review', 'Review'), ('other', 'Other')], default='general', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('blocked', 'Blocked')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('assigned_to', models.CharField(blank=True, max_length=200)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('estimated_hours', models.IntegerField(blank=True, null=True)),
                ('actual_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('completion_percentage', models.IntegerField(default=0)),
                ('dependencies', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimelineActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('evidence_collected', 'Evidence Collected'), ('interview', 'Interview'), ('analysis', 'Analysis'), ('document_created', 'Document Created'), ('task_completed', 'Task Completed'), ('status_change', 'Status Change'), ('other', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('activity_date', models.DateTimeField()),
                ('performed_by', models.CharField(blank=True, max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'timeline_activities',
                'ordering': ['-activity_date'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('investigator', 'Lead Investigator'), ('analyst', 'Forensic Analyst'), ('user', 'Regular User')], default='user', max_length=20)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['case_number'], name='cases_case_nu_25894f_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['status'], name='cases_status_e2ca9e_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['priority'], name='cases_priorit_f0ec1a_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['date_opened'], name='cases_date_op_22db68_idx'),
        ),
        migrations.AddField(
            model_name='caseperson',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_persons', to='forensics.case'),
        ),
        migrations.AddField(
            model_name='document',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='forensics.case'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence', to='forensics.case'),
        ),
        migrations.AddField(
            model_name='document',
            name='evidence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='forensics.evidence'),
        ),
        migrations.AddField(
            model_name='notification',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='forensics.case'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['last_name'], name='persons_last_na_312bc6_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['first_name'], name='persons_first_n_9790a8_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['person_type'], name='persons_person__6d3413_idx'),
        ),
        migrations.AddField(
            model_name='caseperson',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_cases', to='forensics.person'),
        ),
        migrations.AddField(
            model_name='task',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='forensics.case'),
        ),
        migrations.AddField(
            model_name='timelineactivity',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_activities', to='forensics.case'),
        ),
        migrations.AddField(
            model_name='timelineactivity',
            name='related_evidence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forensics.evidence'),
        ),
        migrations.AddField(
            model_name='timelineactivity',
            name='related_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forensics.person'),
        ),
        migrations.AddField(
            model_name='timelineactivity',
            name='related_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forensics.task'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['evidence_number'], name='evidence_evidenc_e24844_idx'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['case'], name='evidence_case_id_7be2ee_idx'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['evidence_type'], name='evidence_evidenc_a2d96a_idx'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['status'], name='evidence_status_2d91c2_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['case'], name='documents_case_id_a4dbef_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_type'], name='documents_documen_fc21d0_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['case'], name='notificatio_case_id_0a4d27_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_read'], name='notificatio_is_read_3f8c44_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='notificatio_created_e4c995_idx'),
        ),
        migrations.AddIndex(
            model_name='caseperson',
            index=models.Index(fields=['case'], name='case_person_case_id_19466e_idx'),
        ),
        migrations.AddIndex(
            model_name='caseperson',
            index=models.Index(fields=['person'], name='case_person_person__d9a8aa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='caseperson',
            unique_together={('case', 'person', 'role')},
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['case'], name='tasks_case_id_498637_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status'], name='tasks_status_031d4c_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['priority'], name='tasks_priorit_a9efa1_idx'),
        ),
        migrations.AddIndex(
            model_name='timelineactivity',
            index=models.Index(fields=['case'], name='timeline_ac_case_id_115195_idx'),
        ),
        migrations.AddIndex(
            model_name='timelineactivity',
            index=models.Index(fields=['activity_date'], name='timeline_ac_activit_595665_idx'),
        ),
    ]
