# Generated by Django 5.2.8 on 2025-11-24 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensics', '0002_case_caseperson_document_evidence_notification_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='lead_investigator',
            new_name='prosecutor',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('investigator', 'Prosecutor'), ('analyst', 'Forensic Analyst'), ('user', 'Regular User')], default='user', max_length=20),
        ),
    ]
