# Generated by Django 5.2.8 on 2025-11-24 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensics', '0003_rename_lead_investigator_case_prosecutor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_number',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
