# Generated by Django 5.2.8 on 2025-11-24 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensics', '0004_alter_case_case_number'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='evidence',
            name='evidence_evidenc_a2d96a_idx',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='chain_of_custody',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='evidence_type',
        ),
        migrations.AddField(
            model_name='evidence',
            name='acquisition_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evidence',
            name='acquisition_method',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='evidence',
            name='acquisition_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='evidence',
            name='acquisition_tool',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='evidence',
            name='brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='evidence',
            name='chain_of_custody_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='evidence',
            name='color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='evidence',
            name='custodian_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custody_evidence', to='forensics.person'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='damage_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='evidence',
            name='damages',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evidence',
            name='device_condition',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='evidence',
            name='device_specific_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='evidence',
            name='device_type',
            field=models.CharField(choices=[('computer', 'Computer'), ('mobile', 'Mobile Device'), ('storage', 'Storage Device'), ('network', 'Network Device'), ('cloud', 'Cloud/Online Account'), ('drone', 'Drone/UAV'), ('gaming', 'Gaming Console'), ('car', 'Vehicle/Automotive'), ('iot', 'IoT Device'), ('memory', 'Memory/RAM'), ('video', 'Video Evidence'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='evidence',
            name='examiner_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='evidence',
            name='firmware_version',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='evidence',
            name='forensic_image_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='evidence',
            name='hash_algorithm',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='evidence',
            name='hash_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evidence',
            name='location',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='evidence',
            name='mac_address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='evidence',
            name='make',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='evidence',
            name='model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='evidence',
            name='owner_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_evidence', to='forensics.person'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='seized_from_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seized_evidence', to='forensics.person'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='seizure_authority',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='evidence',
            name='seizure_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evidence',
            name='seizure_location',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='evidence',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='evidence',
            name='state',
            field=models.CharField(blank=True, choices=[('clean', 'Clean'), ('dirty', 'Dirty'), ('damaged', 'Damaged')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='evidence_number',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='status',
            field=models.CharField(choices=[('collected', 'Collected'), ('processing', 'Processing'), ('analyzed', 'Analyzed'), ('reviewed', 'Reviewed'), ('archived', 'Archived'), ('returned', 'Returned'), ('destroyed', 'Destroyed')], default='collected', max_length=20),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['device_type'], name='evidence_device__1e2f14_idx'),
        ),
    ]
