# Generated by Django 5.2.8 on 2025-11-24 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensics', '0005_remove_evidence_evidence_evidenc_a2d96a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='imei',
            field=models.CharField(blank=True, help_text='Primary IMEI for mobile devices', max_length=100),
        ),
        migrations.AddField(
            model_name='evidence',
            name='imei_numbers',
            field=models.JSONField(blank=True, default=list, help_text='Additional IMEI numbers for dual/multi-SIM devices'),
        ),
    ]
