# Generated by Django 5.2.8 on 2025-11-24 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensics', '0006_evidence_imei_evidence_imei_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='ibs_number',
            field=models.CharField(blank=True, help_text='IBS tracking number (e.g., 24/46/123)', max_length=50),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['ibs_number'], name='evidence_ibs_num_800252_idx'),
        ),
    ]
