# Generated by Django 5.2.8 on 2025-11-24 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensics', '0007_evidence_ibs_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_type',
            field=models.CharField(blank=True, choices=[('fraud', 'Fraud'), ('cybercrime', 'Cybercrime'), ('data_breach', 'Data Breach'), ('intellectual_property', 'Intellectual Property'), ('general', 'General')], default='', max_length=30),
        ),
    ]
