# Generated by Django 5.2.8 on 2025-11-24 06:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensics', '0008_alter_case_case_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='evidence_images/%Y/%m/%d/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.CharField(blank=True, max_length=200)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='forensics.evidence')),
            ],
            options={
                'db_table': 'evidence_images',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
