# Generated by Django 5.2.8 on 2025-11-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensics', '0009_evidenceimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='current_department',
            field=models.CharField(blank=True, choices=[('ibs', 'IBS'), ('team', 'Team'), ('digi', 'DIGI')], help_text='Current department holding the device', max_length=20),
        ),
        migrations.AddField(
            model_name='evidence',
            name='received_by',
            field=models.CharField(blank=True, help_text='Person who received the device', max_length=200),
        ),
        migrations.AddField(
            model_name='evidence',
            name='received_date',
            field=models.DateTimeField(blank=True, help_text='Date device was received by current department', null=True),
        ),
    ]
