# Generated by Django 5.2.8 on 2025-11-24 06:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensics', '0010_evidence_current_department_evidence_received_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_department', models.CharField(blank=True, help_text='Department transferring from', max_length=20)),
                ('to_department', models.CharField(blank=True, help_text='Department transferring to', max_length=20)),
                ('transferred_by', models.CharField(blank=True, max_length=200)),
                ('received_by', models.CharField(blank=True, max_length=200)),
                ('transfer_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='forensics.evidence')),
            ],
            options={
                'db_table': 'evidence_transfers',
                'ordering': ['-transfer_date'],
                'indexes': [models.Index(fields=['evidence'], name='evidence_tr_evidenc_f50c27_idx'), models.Index(fields=['transfer_date'], name='evidence_tr_transfe_ec882a_idx')],
            },
        ),
    ]
