# Generated by Django 5.2.8 on 2025-11-24 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensics', '0013_alter_case_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='department',
            field=models.CharField(blank=True, choices=[('sur', 'SUR'), ('ar', 'AR'), ('jzz', 'JZZ'), ('zwacri', 'ZwaCri'), ('fraude', 'Fraude'), ('umm', 'UMM'), ('alpha', 'Alpha'), ('douane', 'Douane'), ('ind', 'IND'), ('verkeer', 'Verkeer'), ('kustwacht', 'Kustwacht'), ('pelican', 'Pelican'), ('ibs', 'IBS'), ('other', 'Other')], help_text='Department handling the case', max_length=20),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='current_department',
            field=models.CharField(blank=True, choices=[('sur', 'SUR'), ('ar', 'AR'), ('jzz', 'JZZ'), ('zwacri', 'ZwaCri'), ('fraude', 'Fraude'), ('umm', 'UMM'), ('alpha', 'Alpha'), ('douane', 'Douane'), ('ind', 'IND'), ('verkeer', 'Verkeer'), ('kustwacht', 'Kustwacht'), ('pelican', 'Pelican'), ('ibs', 'IBS'), ('other', 'Other')], help_text='Current department holding the device', max_length=20),
        ),
    ]
