# Generated by Django 5.2.8 on 2025-11-29 04:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensics', '0014_alter_case_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(help_text='Full name of the requester', max_length=200)),
                ('badge_number', models.CharField(help_text='Badge or ID number (Required)', max_length=50)),
                ('department', models.CharField(help_text='Department/Unit', max_length=100)),
                ('phone_extension', models.CharField(blank=True, help_text='Office extension (optional)', max_length=30)),
                ('requested_username', models.CharField(help_text='Desired username for login', max_length=150)),
                ('reason', models.TextField(help_text='Reason for requesting system access')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.CharField(blank=True, help_text='Admin who reviewed', max_length=100)),
                ('review_notes', models.TextField(blank=True, help_text='Admin notes on decision')),
                ('temp_password', models.CharField(blank=True, help_text='Temporary password if approved', max_length=50)),
            ],
            options={
                'db_table': 'access_requests',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['status'], name='access_requ_status_6e90d6_idx'), models.Index(fields=['badge_number'], name='access_requ_badge_n_de72bd_idx')],
            },
        ),
    ]
