# Generated by Django 5.2.8 on 2025-11-30 17:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensics', '0015_accessrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyJournal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('title', models.CharField(help_text='Brief title for the day', max_length=255)),
                ('content', models.TextField(help_text='Detailed description of tasks completed')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags for categorizing work')),
                ('is_pinned', models.BooleanField(default=False, help_text='Pin important entries')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'daily_journals',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='forensics.dailyjournal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'journal_comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='dailyjournal',
            index=models.Index(fields=['user', 'date'], name='daily_journ_user_id_df2ac6_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyjournal',
            index=models.Index(fields=['date'], name='daily_journ_date_21ddb5_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyjournal',
            index=models.Index(fields=['is_pinned'], name='daily_journ_is_pinn_b48950_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyjournal',
            unique_together={('user', 'date')},
        ),
        migrations.AddIndex(
            model_name='journalcomment',
            index=models.Index(fields=['journal', 'created_at'], name='journal_com_journal_6f59e1_idx'),
        ),
    ]
