# Generated by Django 5.2.8 on 2026-01-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensics', '0017_alter_document_document_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('ontvangstbewijs', 'Ontvangstbewijs'), ('intake', 'Intake'), ('kvi', 'KVI'), ('na-sporing', 'Na-sporing'), ('procesverbaal', 'Proces-Verbaal'), ('rapport', 'Rapport'), ('onderzoeksverslag', 'Onderzoeksverslag'), ('foto', 'Foto'), ('bewijs', 'Bewijs'), ('verklaring', 'Verklaring'), ('andere', 'Andere')], max_length=20),
        ),
    ]
